const FETCH_BLOGS = 'FETCH_BLOGS';
const SET_DISPLAY_ITEM_COUNT = 'SET_DISPLAY_ITEM_COUNT';
const SET_SORT_BY_FIELD = 'SET_SORT_BY_FIELD';
const SET_FILTER = 'SET_FILTER';
const SET_LIKES = 'SET_LIKES';

export { FETCH_BLOGS, SET_DISPLAY_ITEM_COUNT, SET_SORT_BY_FIELD, SET_FILTER, SET_LIKES };